import {db} from './db.js';
import {consumeProduct} from './recipe-engine.js';

const n=v=>Number(v||0);
function rowOrder(id){return db.prepare(`SELECT o.*,dt.label table_name,e.name employee_name FROM orders o LEFT JOIN dining_tables dt ON dt.id=o.table_id LEFT JOIN employees e ON e.id=o.employee_id WHERE o.id=?`).get(id)}
function recalcOrder(id){const subtotal=n(db.prepare('SELECT COALESCE(SUM(qty*unit_price),0) total FROM order_items WHERE order_id=?').get(id).total);db.prepare('UPDATE orders SET subtotal=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(subtotal,id);return subtotal}
function orderFull(id){const order=rowOrder(id);if(!order)return null;return {...order,items:db.prepare(`SELECT oi.*,p.name product_name,p.category,p.unit_type,p.dose_ml FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=? ORDER BY oi.id`).all(id),payments:db.prepare('SELECT * FROM order_payments WHERE order_id=? ORDER BY id').all(id)}}

export function registerOperations(app,{minRole,audit}){
  app.get('/api/operations/summary',(_req,res)=>{const tables=db.prepare("SELECT COUNT(*) total,SUM(status='OCCUPIED') occupied FROM dining_tables WHERE active=1").get();const orders=db.prepare("SELECT COUNT(*) open_orders,COALESCE(SUM(subtotal),0) open_value FROM orders WHERE status='OPEN'").get();const kitchen=db.prepare("SELECT COUNT(*) pending FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.status='OPEN' AND oi.status IN ('NEW','PREPARING','READY')").get();const low=db.prepare('SELECT COUNT(*) n FROM products WHERE active=1 AND stock<=minimum_stock').get().n;res.json({tables:{total:n(tables.total),occupied:n(tables.occupied)},orders:{count:n(orders.open_orders),value:n(orders.open_value)},kitchen:n(kitchen.pending),lowStock:n(low)})});

  app.get('/api/tables',(_req,res)=>res.json(db.prepare(`SELECT dt.*,o.id order_id,o.customer_name,o.subtotal,o.employee_id,e.name employee_name FROM dining_tables dt LEFT JOIN orders o ON o.table_id=dt.id AND o.status='OPEN' LEFT JOIN employees e ON e.id=o.employee_id WHERE dt.active=1 ORDER BY dt.id`).all()));
  app.post('/api/tables',minRole(80),(req,res)=>{const {label,area='',capacity=4}=req.body||{};if(!String(label||'').trim())return res.status(400).json({error:'LABEL_REQUIRED'});try{const info=db.prepare('INSERT INTO dining_tables(label,area,capacity) VALUES(?,?,?)').run(String(label).trim(),String(area||''),Math.max(1,n(capacity)));audit(req.user.id,'CREATE','TABLE',info.lastInsertRowid,{label});res.status(201).json(db.prepare('SELECT * FROM dining_tables WHERE id=?').get(info.lastInsertRowid))}catch(e){res.status(400).json({error:'TABLE_CREATE_ERROR',message:e.message})}});
  app.post('/api/tables/:id/open',minRole(40),(req,res)=>{const table=db.prepare('SELECT * FROM dining_tables WHERE id=? AND active=1').get(n(req.params.id));if(!table)return res.status(404).json({error:'TABLE_NOT_FOUND'});const existing=db.prepare("SELECT id FROM orders WHERE table_id=? AND status='OPEN'").get(table.id);if(existing)return res.status(409).json({error:'TABLE_ALREADY_OPEN',order:orderFull(existing.id)});const emp=req.body?.employee_id?n(req.body.employee_id):(db.prepare('SELECT id FROM employees WHERE user_id=?').get(req.user.id)?.id||null);const info=db.prepare("INSERT INTO orders(label,customer_name,status,subtotal,employee_id,table_id,notes) VALUES(?,?,'OPEN',0,?,?,?)").run(table.label,String(req.body?.customer_name||''),emp,table.id,String(req.body?.notes||''));db.prepare("UPDATE dining_tables SET status='OCCUPIED' WHERE id=?").run(table.id);audit(req.user.id,'OPEN','TABLE',table.id,{order_id:info.lastInsertRowid});res.status(201).json(orderFull(info.lastInsertRowid))});

  app.get('/api/orders-v03',(_req,res)=>res.json(db.prepare(`SELECT o.*,dt.label table_name,e.name employee_name,(SELECT COUNT(*) FROM order_items oi WHERE oi.order_id=o.id) item_count FROM orders o LEFT JOIN dining_tables dt ON dt.id=o.table_id LEFT JOIN employees e ON e.id=o.employee_id WHERE o.status='OPEN' ORDER BY o.updated_at DESC`).all()));
  app.get('/api/orders-v03/:id',(req,res)=>{const o=orderFull(n(req.params.id));return o?res.json(o):res.status(404).json({error:'ORDER_NOT_FOUND'})});
  app.post('/api/orders-v03/:id/items',minRole(30),(req,res)=>{const id=n(req.params.id),order=rowOrder(id);if(!order||order.status!=='OPEN')return res.status(404).json({error:'ORDER_NOT_FOUND'});const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(n(req.body?.product_id));if(!p)return res.status(404).json({error:'PRODUCT_NOT_FOUND'});const qty=Math.max(.01,n(req.body?.qty||1));const factor=Math.max(.0001,n(p.stock_factor||1));const reserved=n(db.prepare(`SELECT COALESCE(SUM(oi.qty*COALESCE(p.stock_factor,1)),0) total FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN products p ON p.id=oi.product_id WHERE o.status='OPEN' AND oi.product_id=?`).get(p.id).total);if(n(p.stock)<reserved+qty*factor)return res.status(409).json({error:'STOCK_INSUFFICIENT',message:`Estoque insuficiente para ${p.name}.`});const emp=req.body?.employee_id?n(req.body.employee_id):(order.employee_id||null);const info=db.prepare("INSERT INTO order_items(order_id,product_id,qty,unit_price,notes,status,employee_id) VALUES(?,?,?,?,?,'NEW',?)").run(id,p.id,qty,n(p.price),String(req.body?.notes||''),emp);recalcOrder(id);audit(req.user.id,'ADD_ITEM','ORDER',id,{item_id:info.lastInsertRowid,product:p.name,qty});res.status(201).json(orderFull(id))});
  app.patch('/api/order-items/:id/status',minRole(30),(req,res)=>{const allowed=['NEW','PREPARING','READY','SERVED','CANCELLED'];const status=String(req.body?.status||'').toUpperCase();if(!allowed.includes(status))return res.status(400).json({error:'INVALID_STATUS'});const item=db.prepare('SELECT * FROM order_items WHERE id=?').get(n(req.params.id));if(!item)return res.status(404).json({error:'ITEM_NOT_FOUND'});db.prepare('UPDATE order_items SET status=? WHERE id=?').run(status,item.id);audit(req.user.id,'STATUS','ORDER_ITEM',item.id,{status});res.json(db.prepare('SELECT * FROM order_items WHERE id=?').get(item.id))});
  app.delete('/api/order-items/:id',minRole(40),(req,res)=>{const item=db.prepare('SELECT * FROM order_items WHERE id=?').get(n(req.params.id));if(!item)return res.status(404).json({error:'ITEM_NOT_FOUND'});db.prepare('DELETE FROM order_items WHERE id=?').run(item.id);recalcOrder(item.order_id);audit(req.user.id,'DELETE','ORDER_ITEM',item.id);res.json(orderFull(item.order_id))});
  app.post('/api/orders-v03/:id/transfer',minRole(40),(req,res)=>{const id=n(req.params.id),to=n(req.body?.table_id);const order=rowOrder(id),target=db.prepare('SELECT * FROM dining_tables WHERE id=? AND active=1').get(to);if(!order||!target)return res.status(404).json({error:'NOT_FOUND'});const busy=db.prepare("SELECT id FROM orders WHERE table_id=? AND status='OPEN' AND id<>?").get(to,id);if(busy)return res.status(409).json({error:'TARGET_TABLE_BUSY'});if(order.table_id)db.prepare("UPDATE dining_tables SET status='FREE' WHERE id=?").run(order.table_id);db.prepare("UPDATE dining_tables SET status='OCCUPIED' WHERE id=?").run(to);db.prepare('UPDATE orders SET table_id=?,label=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(to,target.label,id);audit(req.user.id,'TRANSFER','ORDER',id,{to_table:to});res.json(orderFull(id))});
  app.post('/api/orders-v03/:id/split',minRole(40),(req,res)=>{const id=n(req.params.id),itemIds=(req.body?.item_ids||[]).map(n).filter(Boolean);if(!itemIds.length)return res.status(400).json({error:'ITEMS_REQUIRED'});const source=rowOrder(id);if(!source)return res.status(404).json({error:'ORDER_NOT_FOUND'});const info=db.prepare("INSERT INTO orders(label,customer_name,status,subtotal,employee_id,notes) VALUES(?,?,'OPEN',0,?,?)").run(String(req.body?.label||`${source.label} - Divisão`),String(req.body?.customer_name||''),source.employee_id,'Conta dividida');const q=itemIds.map(()=>'?').join(',');db.prepare(`UPDATE order_items SET order_id=? WHERE order_id=? AND id IN (${q})`).run(info.lastInsertRowid,id,...itemIds);recalcOrder(id);recalcOrder(info.lastInsertRowid);audit(req.user.id,'SPLIT','ORDER',id,{new_order_id:info.lastInsertRowid});res.json({source:orderFull(id),created:orderFull(info.lastInsertRowid)})});
  app.post('/api/orders-v03/:id/close',minRole(40),(req,res)=>{const id=n(req.params.id),order=orderFull(id);if(!order||order.status!=='OPEN')return res.status(404).json({error:'ORDER_NOT_FOUND'});if(!order.items.length)return res.status(400).json({error:'EMPTY_ORDER'});const cs=db.prepare("SELECT * FROM cash_sessions WHERE status='OPEN' ORDER BY id DESC LIMIT 1").get();if(!cs)return res.status(409).json({error:'CASH_SESSION_REQUIRED',message:'Abra o caixa antes de fechar a comanda.'});const payment=String(req.body?.payment_method||'DINHEIRO');const tip=n(req.body?.tip_amount);try{const sale=db.transaction(()=>{const active=order.items.filter(i=>i.status!=='CANCELLED');const total=active.reduce((a,i)=>a+n(i.qty)*n(i.unit_price),0);const s=db.prepare("INSERT INTO sales(total,payment_method,status,table_label,customer_name,cash_session_id,user_id,employee_id,tip_amount) VALUES(?,?,'PAID',?,?,?,?,?,?)").run(total,payment,order.table_name||order.label,order.customer_name,cs.id,req.user.id,order.employee_id,tip);for(const item of active){const p=db.prepare('SELECT * FROM products WHERE id=?').get(item.product_id),use=n(item.qty)*Math.max(.0001,n(p.stock_factor||1));db.prepare('INSERT INTO sale_items(sale_id,product_id,qty,unit_price,unit_cost) VALUES(?,?,?,?,?)').run(s.lastInsertRowid,p.id,item.qty,item.unit_price,p.cost);consumeProduct(p.id,item.qty,req.user.id,'ORDER',id)}if(order.employee_id&&tip>0)db.prepare("INSERT INTO tips(sale_id,employee_id,amount,method,status) VALUES(?,?,?,'ORDER','PENDING')").run(s.lastInsertRowid,order.employee_id,tip);db.prepare("UPDATE orders SET status='CLOSED',closed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(id);if(order.table_id)db.prepare("UPDATE dining_tables SET status='FREE' WHERE id=?").run(order.table_id);return db.prepare('SELECT * FROM sales WHERE id=?').get(s.lastInsertRowid)})();audit(req.user.id,'CLOSE','ORDER',id,{sale_id:sale.id,total:sale.total,payment});res.json({sale,order:orderFull(id)})}catch(e){res.status(409).json({error:'ORDER_CLOSE_ERROR',message:e.message})}});

  app.get('/api/kitchen',minRole(30),(_req,res)=>res.json(db.prepare(`SELECT oi.id,oi.order_id,oi.qty,oi.notes,oi.status,oi.created_at,p.name product_name,p.category,o.label order_label,dt.label table_name,e.name employee_name FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN products p ON p.id=oi.product_id LEFT JOIN dining_tables dt ON dt.id=o.table_id LEFT JOIN employees e ON e.id=oi.employee_id WHERE o.status='OPEN' AND oi.status NOT IN ('SERVED','CANCELLED') ORDER BY CASE oi.status WHEN 'NEW' THEN 1 WHEN 'PREPARING' THEN 2 WHEN 'READY' THEN 3 ELSE 4 END,oi.id`).all()));

  app.get('/api/beverage-control',minRole(55),(_req,res)=>res.json(db.prepare(`SELECT id,name,category,unit_type,stock,stock_unit,package_ml,dose_ml,stock_factor,price,cost,minimum_stock,CASE WHEN dose_ml>0 AND stock_unit='ML' THEN stock/dose_ml ELSE stock END theoretical_servings FROM products WHERE active=1 AND (dose_ml IS NOT NULL OR unit_type IN ('DOSE','ML','BOTTLE','KEG')) ORDER BY category,name`).all()));
  app.patch('/api/products/:id/beverage',minRole(55),(req,res)=>{const id=n(req.params.id),p=db.prepare('SELECT * FROM products WHERE id=?').get(id);if(!p)return res.status(404).json({error:'PRODUCT_NOT_FOUND'});const dose=n(req.body?.dose_ml||p.dose_ml||1),stockUnit=String(req.body?.stock_unit||'ML').toUpperCase(),factor=stockUnit==='ML'?dose:n(req.body?.stock_factor||1);db.prepare('UPDATE products SET unit_type=?,package_ml=?,dose_ml=?,stock_unit=?,stock_factor=? WHERE id=?').run(String(req.body?.unit_type||'DOSE'),n(req.body?.package_ml||p.package_ml),dose,stockUnit,factor,id);audit(req.user.id,'UPDATE','BEVERAGE',id,{dose,stockUnit,factor});res.json(db.prepare('SELECT * FROM products WHERE id=?').get(id))});
  app.post('/api/products/:id/stock-adjust',minRole(55),(req,res)=>{const id=n(req.params.id),qty=n(req.body?.qty),p=db.prepare('SELECT * FROM products WHERE id=?').get(id);if(!p)return res.status(404).json({error:'PRODUCT_NOT_FOUND'});if(!qty)return res.status(400).json({error:'QTY_REQUIRED'});if(n(p.stock)+qty<0)return res.status(409).json({error:'NEGATIVE_STOCK'});db.prepare('UPDATE products SET stock=stock+? WHERE id=?').run(qty,id);db.prepare("INSERT INTO stock_movements(product_id,type,qty,reference_type,reference_id,user_id,notes) VALUES(?,'ADJUSTMENT',?,'MANUAL',NULL,?,?)").run(id,qty,req.user.id,String(req.body?.notes||'Ajuste manual'));audit(req.user.id,'ADJUST','STOCK',id,{qty});res.json(db.prepare('SELECT * FROM products WHERE id=?').get(id))});

  app.get('/api/suppliers-v03',minRole(55),(_req,res)=>res.json(db.prepare('SELECT * FROM suppliers WHERE active=1 ORDER BY name').all()));
  app.post('/api/suppliers-v03',minRole(55),(req,res)=>{const {name,contact='',phone='',email=''}=req.body||{};if(!String(name||'').trim())return res.status(400).json({error:'NAME_REQUIRED'});const info=db.prepare('INSERT INTO suppliers(name,contact,phone,email) VALUES(?,?,?,?)').run(String(name).trim(),contact,phone,email);audit(req.user.id,'CREATE','SUPPLIER',info.lastInsertRowid,{name});res.status(201).json(db.prepare('SELECT * FROM suppliers WHERE id=?').get(info.lastInsertRowid))});
  app.get('/api/quotes-v03',minRole(55),(_req,res)=>res.json(db.prepare(`SELECT q.*,COUNT(qi.id) offers,MIN(qi.unit_price) best_unit_price FROM purchase_quotes q LEFT JOIN quote_items qi ON qi.quote_id=q.id GROUP BY q.id ORDER BY q.id DESC`).all()));
  app.post('/api/quotes-v03',minRole(55),(req,res)=>{const title=String(req.body?.title||'').trim();if(!title)return res.status(400).json({error:'TITLE_REQUIRED'});const info=db.prepare("INSERT INTO purchase_quotes(title,status) VALUES(?,'OPEN')").run(title);audit(req.user.id,'CREATE','QUOTE',info.lastInsertRowid,{title});res.status(201).json(db.prepare('SELECT * FROM purchase_quotes WHERE id=?').get(info.lastInsertRowid))});
  app.get('/api/quotes-v03/:id',(req,res)=>{const q=db.prepare('SELECT * FROM purchase_quotes WHERE id=?').get(n(req.params.id));if(!q)return res.status(404).json({error:'QUOTE_NOT_FOUND'});const items=db.prepare(`SELECT qi.*,s.name supplier_name,p.name product_name,(qi.qty*qi.unit_price+qi.freight) total_offer FROM quote_items qi JOIN suppliers s ON s.id=qi.supplier_id LEFT JOIN products p ON p.id=qi.product_id WHERE qi.quote_id=? ORDER BY description,total_offer`).all(q.id);res.json({...q,items})});
  app.post('/api/quotes-v03/:id/items',minRole(55),(req,res)=>{const {supplier_id,product_id=null,description='',qty=1,unit_price=0,freight=0,lead_days=null,notes=''}=req.body||{};if(!supplier_id||!String(description||'').trim())return res.status(400).json({error:'INVALID_QUOTE_ITEM'});const info=db.prepare('INSERT INTO quote_items(quote_id,supplier_id,product_id,description,qty,unit_price,freight,lead_days,notes) VALUES(?,?,?,?,?,?,?,?,?)').run(n(req.params.id),n(supplier_id),product_id?n(product_id):null,description,n(qty),n(unit_price),n(freight),lead_days==null?null:n(lead_days),notes);audit(req.user.id,'ADD_OFFER','QUOTE',req.params.id,{item_id:info.lastInsertRowid});res.status(201).json({id:info.lastInsertRowid})});
  app.get('/api/quotes-v03/:id/best',minRole(55),(req,res)=>res.json(db.prepare(`SELECT * FROM (SELECT qi.*,s.name supplier_name,(qi.qty*qi.unit_price+qi.freight) total_offer,ROW_NUMBER() OVER(PARTITION BY lower(qi.description) ORDER BY (qi.qty*qi.unit_price+qi.freight),COALESCE(qi.lead_days,999)) rn FROM quote_items qi JOIN suppliers s ON s.id=qi.supplier_id WHERE qi.quote_id=?) WHERE rn=1 ORDER BY description`).all(n(req.params.id))));
}
