import {db} from './db.js';import {createUnifiedSale,cashSummary,currentCash} from './transaction-engine.js';
const n=v=>Number(v||0);
export function registerOperationalV1(app,{minRole,audit}){
 app.get('/api/operation/status',(req,res)=>{const cash=currentCash();res.json({cash,cash_summary:cash?cashSummary(cash.id):null,open_orders:db.prepare("SELECT COUNT(*) n FROM orders WHERE status='OPEN'").get().n,kitchen_pending:db.prepare("SELECT COUNT(*) n FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.status='OPEN' AND oi.status NOT IN ('SERVED','CANCELLED')").get().n,low_stock:db.prepare('SELECT COUNT(*) n FROM products WHERE active=1 AND stock<=minimum_stock').get().n})});
 app.get('/api/cash-sessions/:id/summary',minRole(50),(req,res)=>{const s=cashSummary(req.params.id);return s?res.json(s):res.status(404).json({error:'CASH_NOT_FOUND'})});
 app.post('/api/sales-v1',minRole(40),(req,res)=>{try{const emp=req.body?.employee_id?Number(req.body.employee_id):(db.prepare('SELECT id FROM employees WHERE user_id=?').get(req.user.id)?.id||null);const sale=createUnifiedSale({...req.body,user_id:req.user.id,employee_id:emp,source:'POS'});audit(req.user.id,'CREATE','SALE_V1',sale.id,{total:sale.total,payment_method:sale.payment_method});res.status(201).json({sale,cash_summary:cashSummary(sale.cash_session_id)})}catch(e){res.status(409).json({error:'SALE_V1_ERROR',message:e.message})}});
 app.post('/api/orders-v1/:id/close',minRole(40),(req,res)=>{const id=n(req.params.id);const order=db.prepare("SELECT * FROM orders WHERE id=? AND status='OPEN'").get(id);if(!order)return res.status(404).json({error:'ORDER_NOT_FOUND'});const items=db.prepare("SELECT oi.*,p.name FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=? AND oi.status<>'CANCELLED'").all(id);if(!items.length)return res.status(400).json({error:'EMPTY_ORDER'});try{const sale=createUnifiedSale({items:items.map(x=>({product_id:x.product_id,qty:x.qty,mode:x.sale_mode||'UNIT'})),payment_method:req.body?.payment_method||'DINHEIRO',payments:req.body?.payments||[],table_label:order.label,customer_name:order.customer_name,employee_id:order.employee_id,tip_amount:req.body?.tip_amount||0,user_id:req.user.id,source:'ORDER',source_id:id});db.prepare("UPDATE orders SET status='CLOSED',closed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(id);if(order.table_id)db.prepare("UPDATE dining_tables SET status='FREE' WHERE id=?").run(order.table_id);audit(req.user.id,'CLOSE','ORDER_V1',id,{sale_id:sale.id});res.json({sale,order_id:id})}catch(e){res.status(409).json({error:'ORDER_CLOSE_ERROR',message:e.message})}});
 app.post('/api/cash-sessions/:id/close-v1',minRole(50),(req,res)=>{const id=n(req.params.id),sum=cashSummary(id);if(!sum||sum.session.status!=='OPEN')return res.status(404).json({error:'CASH_NOT_OPEN'});const counted=n(req.body?.counted_cash ?? req.body?.closing_amount),difference=counted-sum.expected_cash;db.prepare("UPDATE cash_sessions SET status='CLOSED',closing_amount=?,expected_amount=?,closed_at=CURRENT_TIMESTAMP,notes=COALESCE(?,notes) WHERE id=?").run(counted,sum.expected_cash,String(req.body?.notes||''),id);audit(req.user.id,'CLOSE','CASH_SESSION_V1',id,{expected_cash:sum.expected_cash,counted_cash:counted,difference});res.json({...sum,session:db.prepare('SELECT * FROM cash_sessions WHERE id=?').get(id),counted_cash:counted,difference})});
 app.patch('/api/products/:id/full',minRole(55),(req,res)=>{const id=n(req.params.id),p=db.prepare('SELECT * FROM products WHERE id=?').get(id);if(!p)return res.status(404).json({error:'PRODUCT_NOT_FOUND'});const allowed=['name','category','barcode','image_url','description','unit_type','package_ml','dose_ml','price','cost','stock','minimum_stock','active'];const entries=Object.entries(req.body||{}).filter(([k])=>allowed.includes(k));if(!entries.length)return res.json(p);db.prepare(`UPDATE products SET ${entries.map(([k])=>`${k}=?`).join(',')} WHERE id=?`).run(...entries.map(([,v])=>v),id);audit(req.user.id,'UPDATE','PRODUCT_FULL',id);res.json(db.prepare('SELECT * FROM products WHERE id=?').get(id))});
 app.post('/api/purchases/receive',minRole(55),(req,res)=>{const {supplier_id=null,items=[],notes=''}=req.body||{};if(!items.length)return res.status(400).json({error:'ITEMS_REQUIRED'});try{const out=db.transaction(()=>{let total=0;for(const i of items){const id=n(i.product_id),qty=n(i.qty),cost=n(i.unit_cost);if(qty<=0)throw new Error('INVALID_QTY');total+=qty*cost;db.prepare('UPDATE products SET stock=stock+?,cost=? WHERE id=?').run(qty,cost,id);db.prepare("INSERT INTO stock_movements(product_id,type,qty,reference_type,user_id,notes) VALUES(?,'PURCHASE',?,'PURCHASE_RECEIPT',?,?)").run(id,qty,req.user.id,notes)}const po=db.prepare("INSERT INTO purchase_orders(supplier_id,status,total,received_at,notes) VALUES(?,'RECEIVED',?,CURRENT_TIMESTAMP,?)").run(supplier_id||1,total,notes);return{id:po.lastInsertRowid,total}})();audit(req.user.id,'RECEIVE','PURCHASE',out.id,out);res.status(201).json(out)}catch(e){res.status(409).json({error:'PURCHASE_RECEIVE_ERROR',message:e.message})}});
 app.get('/api/backup/export',minRole(100),(req,res)=>{res.json({ok:true,message:'Use o backup automático do instalador para cópia física do banco.',database:'data/nexus-hospitality.sqlite',schema:'1.0.0'})});
}
