import crypto from 'node:crypto';
import {db} from './db.js';
import {createUnifiedSale} from './transaction-engine.js';
const n=v=>Number(v||0);
const code=()=>`NX-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;
export function initOperationsV11(){
 db.exec(`
 CREATE TABLE IF NOT EXISTS ticket_lots(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL,name TEXT NOT NULL,price REAL NOT NULL DEFAULT 0,quantity INTEGER NOT NULL DEFAULT 0,sold INTEGER NOT NULL DEFAULT 0,starts_at TEXT,ends_at TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE);
 CREATE TABLE IF NOT EXISTS ticket_access_log(id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id INTEGER,event_id INTEGER,code TEXT NOT NULL,result TEXT NOT NULL,user_id INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS delivery_items(id INTEGER PRIMARY KEY AUTOINCREMENT,delivery_id INTEGER NOT NULL,product_id INTEGER NOT NULL,qty REAL NOT NULL DEFAULT 1,unit_price REAL NOT NULL DEFAULT 0,sale_mode TEXT NOT NULL DEFAULT 'UNIT',notes TEXT,FOREIGN KEY(delivery_id) REFERENCES delivery_orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
 `);
 const add=(t,c,d)=>{const cols=db.prepare(`PRAGMA table_info(${t})`).all().map(x=>x.name);if(!cols.includes(c))db.exec(`ALTER TABLE ${t} ADD COLUMN ${c} ${d}`)};
 add('tickets','lot_id','INTEGER');add('tickets','attendee_phone','TEXT');add('tickets','payment_method','TEXT');add('tickets','checked_in_by','INTEGER');
 add('products','menu_visible','INTEGER NOT NULL DEFAULT 1');add('products','menu_featured','INTEGER NOT NULL DEFAULT 0');
 add('delivery_orders','delivery_fee','REAL NOT NULL DEFAULT 0');add('delivery_orders','change_for','REAL');add('delivery_orders','courier_name','TEXT');add('delivery_orders','sale_id','INTEGER');
 add('dining_tables','position_x','INTEGER NOT NULL DEFAULT 0');add('dining_tables','position_y','INTEGER NOT NULL DEFAULT 0');
}
export function registerPublicV11(app){
 app.get('/api/public/menu',(_req,res)=>{const business=db.prepare("SELECT value FROM settings WHERE key='business_name'").get()?.value||'NEXUS Hospitality';const rows=db.prepare(`SELECT id,name,category,description,image_url,price,stock,menu_featured FROM products WHERE active=1 AND menu_visible=1 ORDER BY menu_featured DESC,category,name`).all();res.json({business,products:rows.map(x=>({...x,available:n(x.stock)>0}))})});
}
export function registerOperationsV11(app,{minRole,audit}){
 app.get('/api/v11/tickets/events',minRole(40),(_req,res)=>res.json(db.prepare(`SELECT e.*,COUNT(DISTINCT t.id) tickets,COALESCE(SUM(CASE WHEN t.payment_status='PAID' THEN t.price ELSE 0 END),0) revenue,SUM(CASE WHEN t.checkin_at IS NOT NULL THEN 1 ELSE 0 END) checked_in FROM events e LEFT JOIN tickets t ON t.event_id=e.id GROUP BY e.id ORDER BY COALESCE(e.starts_at,e.created_at) DESC`).all()));
 app.get('/api/v11/tickets/lots/:eventId',minRole(40),(req,res)=>res.json(db.prepare('SELECT * FROM ticket_lots WHERE event_id=? ORDER BY id').all(n(req.params.eventId))));
 app.post('/api/v11/tickets/lots',minRole(60),(req,res)=>{const b=req.body||{};if(!b.event_id||!String(b.name||'').trim())return res.status(400).json({error:'LOT_DATA_REQUIRED'});const i=db.prepare('INSERT INTO ticket_lots(event_id,name,price,quantity,starts_at,ends_at,status) VALUES(?,?,?,?,?,?,?)').run(n(b.event_id),String(b.name).trim(),n(b.price),Math.max(0,n(b.quantity)),b.starts_at||null,b.ends_at||null,b.status||'ACTIVE');audit(req.user.id,'CREATE','TICKET_LOT',i.lastInsertRowid,b);res.status(201).json({id:i.lastInsertRowid})});
 app.get('/api/v11/tickets/:eventId',minRole(40),(req,res)=>res.json(db.prepare(`SELECT t.*,l.name lot_name,e.title event_title FROM tickets t LEFT JOIN ticket_lots l ON l.id=t.lot_id JOIN events e ON e.id=t.event_id WHERE t.event_id=? ORDER BY t.id DESC`).all(n(req.params.eventId))));
 app.post('/api/v11/tickets',minRole(40),(req,res)=>{const b=req.body||{},lot=b.lot_id?db.prepare('SELECT * FROM ticket_lots WHERE id=?').get(n(b.lot_id)):null;if(!b.event_id||!String(b.attendee_name||'').trim())return res.status(400).json({error:'TICKET_DATA_REQUIRED'});if(lot&&lot.quantity>0&&lot.sold>=lot.quantity)return res.status(409).json({error:'LOT_SOLD_OUT'});const ticketCode=code(),price=lot?n(lot.price):n(b.price);const i=db.prepare(`INSERT INTO tickets(event_id,lot_id,attendee_name,attendee_phone,ticket_code,ticket_type,price,payment_status,payment_method) VALUES(?,?,?,?,?,?,?,?,?)`).run(n(b.event_id),b.lot_id?n(b.lot_id):null,String(b.attendee_name).trim(),b.attendee_phone||null,ticketCode,lot?.name||b.ticket_type||'INGRESSO',price,b.payment_status||'PAID',b.payment_method||'PIX');if(lot)db.prepare('UPDATE ticket_lots SET sold=sold+1 WHERE id=?').run(lot.id);audit(req.user.id,'CREATE','TICKET',i.lastInsertRowid,{event_id:b.event_id,code:ticketCode});res.status(201).json(db.prepare('SELECT * FROM tickets WHERE id=?').get(i.lastInsertRowid))});
 app.post('/api/v11/access/checkin',minRole(40),(req,res)=>{const c=String(req.body?.code||'').trim().toUpperCase();const t=db.prepare(`SELECT t.*,e.title event_title FROM tickets t JOIN events e ON e.id=t.event_id WHERE upper(t.ticket_code)=?`).get(c);if(!t){db.prepare("INSERT INTO ticket_access_log(code,result,user_id) VALUES(?,'INVALID',?)").run(c,req.user.id);return res.status(404).json({ok:false,result:'INVALID',message:'Ingresso inválido.'})}if(t.payment_status!=='PAID'&&t.payment_status!=='COURTESY'){db.prepare("INSERT INTO ticket_access_log(ticket_id,event_id,code,result,user_id) VALUES(?,?,?,'PAYMENT_PENDING',?)").run(t.id,t.event_id,c,req.user.id);return res.status(409).json({ok:false,result:'PAYMENT_PENDING',message:'Pagamento não confirmado.',ticket:t})}if(t.checkin_at){db.prepare("INSERT INTO ticket_access_log(ticket_id,event_id,code,result,user_id) VALUES(?,?,?,'DUPLICATE',?)").run(t.id,t.event_id,c,req.user.id);return res.status(409).json({ok:false,result:'DUPLICATE',message:'Ingresso já utilizado.',ticket:t})}db.prepare('UPDATE tickets SET checkin_at=CURRENT_TIMESTAMP,checked_in_by=? WHERE id=?').run(req.user.id,t.id);db.prepare("INSERT INTO ticket_access_log(ticket_id,event_id,code,result,user_id) VALUES(?,?,?,'ALLOWED',?)").run(t.id,t.event_id,c,req.user.id);audit(req.user.id,'CHECKIN','TICKET',t.id,{code:c});res.json({ok:true,result:'ALLOWED',message:'Acesso liberado.',ticket:{...t,checkin_at:new Date().toISOString()}})});
 app.get('/api/v11/menu',minRole(40),(_req,res)=>res.json(db.prepare('SELECT * FROM products WHERE active=1 ORDER BY category,name').all()));
 app.patch('/api/v11/menu/:id',minRole(55),(req,res)=>{const b=req.body||{};db.prepare('UPDATE products SET menu_visible=COALESCE(?,menu_visible),menu_featured=COALESCE(?,menu_featured),description=COALESCE(?,description),price=COALESCE(?,price),image_url=COALESCE(?,image_url) WHERE id=?').run(b.menu_visible==null?null:(b.menu_visible?1:0),b.menu_featured==null?null:(b.menu_featured?1:0),b.description??null,b.price==null?null:n(b.price),b.image_url??null,n(req.params.id));audit(req.user.id,'UPDATE','MENU_PRODUCT',req.params.id,b);res.json({ok:true})});
 app.get('/api/v11/salon',minRole(40),(_req,res)=>res.json(db.prepare(`SELECT dt.*,o.id order_id,o.customer_name,o.subtotal,o.employee_id,o.created_at order_opened_at,e.name employee_name,(SELECT COUNT(*) FROM order_items oi WHERE oi.order_id=o.id AND oi.status<>'CANCELLED') item_count FROM dining_tables dt LEFT JOIN orders o ON o.table_id=dt.id AND o.status='OPEN' LEFT JOIN employees e ON e.id=o.employee_id WHERE dt.active=1 ORDER BY dt.area,dt.id`).all()));
 app.patch('/api/v11/tables/:id',minRole(80),(req,res)=>{const b=req.body||{};db.prepare('UPDATE dining_tables SET label=COALESCE(?,label),area=COALESCE(?,area),capacity=COALESCE(?,capacity),status=COALESCE(?,status) WHERE id=?').run(b.label??null,b.area??null,b.capacity==null?null:n(b.capacity),b.status??null,n(req.params.id));audit(req.user.id,'UPDATE','TABLE',req.params.id,b);res.json({ok:true})});
 app.get('/api/v11/delivery',minRole(40),(_req,res)=>res.json(db.prepare(`SELECT d.*,COALESCE((SELECT SUM(di.qty*di.unit_price) FROM delivery_items di WHERE di.delivery_id=d.id),0) items_total FROM delivery_orders d ORDER BY d.id DESC LIMIT 200`).all()));
 app.get('/api/v11/delivery/:id',minRole(40),(req,res)=>{const d=db.prepare('SELECT * FROM delivery_orders WHERE id=?').get(n(req.params.id));if(!d)return res.status(404).json({error:'DELIVERY_NOT_FOUND'});res.json({...d,items:db.prepare(`SELECT di.*,p.name product_name FROM delivery_items di JOIN products p ON p.id=di.product_id WHERE di.delivery_id=? ORDER BY di.id`).all(d.id)})});
 app.post('/api/v11/delivery',minRole(40),(req,res)=>{const b=req.body||{},items=Array.isArray(b.items)?b.items:[];if(!String(b.customer_name||'').trim()||!items.length)return res.status(400).json({error:'DELIVERY_DATA_REQUIRED'});const out=db.transaction(()=>{const resolved=items.map(x=>{const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(n(x.product_id));if(!p)throw new Error('Produto inválido');return{...x,p,qty:Math.max(.01,n(x.qty)),price:n(x.unit_price||p.price)}});const itemsTotal=resolved.reduce((s,x)=>s+x.qty*x.price,0),fee=n(b.delivery_fee),total=itemsTotal+fee;const i=db.prepare(`INSERT INTO delivery_orders(customer_name,phone,order_type,address,status,total,payment_method,notes,delivery_fee,change_for,courier_name) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(String(b.customer_name).trim(),b.phone||null,b.order_type||'DELIVERY',b.address||null,'NEW',total,b.payment_method||'PIX',b.notes||null,fee,b.change_for? n(b.change_for):null,b.courier_name||null);for(const x of resolved)db.prepare('INSERT INTO delivery_items(delivery_id,product_id,qty,unit_price,sale_mode,notes) VALUES(?,?,?,?,?,?)').run(i.lastInsertRowid,x.p.id,x.qty,x.price,x.mode||'UNIT',x.notes||null);return{id:i.lastInsertRowid,total}})();audit(req.user.id,'CREATE','DELIVERY_V11',out.id,out);res.status(201).json(out)});
 app.patch('/api/v11/delivery/:id/status',minRole(40),(req,res)=>{const id=n(req.params.id),status=String(req.body?.status||'NEW').toUpperCase(),d=db.prepare('SELECT * FROM delivery_orders WHERE id=?').get(id);if(!d)return res.status(404).json({error:'DELIVERY_NOT_FOUND'});if(status==='DELIVERED'&&!d.sale_id){const items=db.prepare('SELECT product_id,qty,sale_mode mode FROM delivery_items WHERE delivery_id=?').all(id);try{const sale=createUnifiedSale({items,payment_method:d.payment_method||'PIX',customer_name:d.customer_name,user_id:req.user.id,source:'DELIVERY',source_id:id});db.prepare("UPDATE delivery_orders SET status='DELIVERED',sale_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(sale.id,id);audit(req.user.id,'DELIVER','DELIVERY',id,{sale_id:sale.id});return res.json({ok:true,sale_id:sale.id})}catch(e){return res.status(409).json({error:'DELIVERY_CLOSE_ERROR',message:e.message})}}db.prepare('UPDATE delivery_orders SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(status,id);audit(req.user.id,'UPDATE_STATUS','DELIVERY',id,{status});res.json({ok:true})});
}
