import {db} from './db.js';import {consumeSmartInventory} from './suite-v06.js';
const n=v=>Number(v||0);
function recipe(id){const r=db.prepare(`SELECT r.*,p.name product_name,p.price product_price FROM recipes r JOIN products p ON p.id=r.product_id WHERE r.id=?`).get(n(id));if(!r)return null;r.items=db.prepare(`SELECT ri.*,p.name ingredient_name,p.cost ingredient_cost,p.stock,p.stock_unit,p.dose_ml FROM recipe_items ri JOIN products p ON p.id=ri.ingredient_product_id WHERE ri.recipe_id=? ORDER BY ri.id`).all(r.id);r.cost=r.items.reduce((a,i)=>a+n(i.qty)*(1+n(i.waste_percent)/100)*n(i.ingredient_cost),0)/Math.max(.0001,n(r.yield_qty));r.margin=n(r.product_price)-r.cost;r.margin_percent=n(r.product_price)?r.margin/n(r.product_price)*100:0;return r}
export function consumeProduct(productId,qty,userId,refType,refId,mode='UNIT'){const p=db.prepare('SELECT * FROM products WHERE id=?').get(n(productId));if(!p)throw new Error('Produto não encontrado');const r=db.prepare('SELECT id,yield_qty FROM recipes WHERE product_id=? AND active=1').get(p.id);if(!r){if(consumeSmartInventory(p.id,qty,userId,refType,refId,mode))return;const use=n(qty)*Math.max(.0001,n(p.stock_factor||1));if(n(p.stock)<use)throw new Error(`Estoque insuficiente: ${p.name}`);db.prepare('UPDATE products SET stock=stock-? WHERE id=?').run(use,p.id);db.prepare("INSERT INTO stock_movements(product_id,type,qty,reference_type,reference_id,user_id,notes) VALUES(?,'SALE',?,?,?,?,'Baixa automática')").run(p.id,-use,refType,String(refId),userId);return}
 const items=db.prepare(`SELECT ri.*,p.name,p.stock FROM recipe_items ri JOIN products p ON p.id=ri.ingredient_product_id WHERE recipe_id=?`).all(r.id);const mult=n(qty)/Math.max(.0001,n(r.yield_qty));for(const i of items){const use=n(i.qty)*mult*(1+n(i.waste_percent)/100);const prof=db.prepare('SELECT product_id FROM inventory_profiles WHERE product_id=?').get(i.ingredient_product_id);if(!prof&&n(i.stock)<use)throw new Error(`Ingrediente insuficiente: ${i.name}`)}for(const i of items){const use=n(i.qty)*mult*(1+n(i.waste_percent)/100);if(consumeSmartInventory(i.ingredient_product_id,use,userId,refType,refId,'BASE'))continue;db.prepare('UPDATE products SET stock=stock-? WHERE id=?').run(use,i.ingredient_product_id);db.prepare("INSERT INTO stock_movements(product_id,type,qty,reference_type,reference_id,user_id,notes) VALUES(?,'RECIPE_CONSUMPTION',?,?,?,?,'Consumo por ficha técnica')").run(i.ingredient_product_id,-use,refType,String(refId),userId)}}
export function registerRecipeEngine(app,minRole,audit){
 app.get('/api/recipes',minRole(40),(_q,res)=>res.json(db.prepare(`SELECT r.id,r.product_id,r.title,r.recipe_type,r.yield_qty,p.name product_name,p.price product_price,(SELECT COUNT(*) FROM recipe_items x WHERE x.recipe_id=r.id) ingredients FROM recipes r JOIN products p ON p.id=r.product_id WHERE r.active=1 ORDER BY r.title`).all()));
 app.get('/api/recipes/:id',minRole(40),(req,res)=>{const r=recipe(req.params.id);return r?res.json(r):res.status(404).json({error:'RECIPE_NOT_FOUND'})});
 app.post('/api/recipes',minRole(55),(req,res)=>{const {product_id,title,recipe_type='FOOD',yield_qty=1,instructions=''}=req.body||{};if(!product_id||!title)return res.status(400).json({error:'INVALID_RECIPE'});const info=db.prepare(`INSERT INTO recipes(product_id,title,recipe_type,yield_qty,instructions) VALUES(?,?,?,?,?) ON CONFLICT(product_id) DO UPDATE SET title=excluded.title,recipe_type=excluded.recipe_type,yield_qty=excluded.yield_qty,instructions=excluded.instructions,updated_at=CURRENT_TIMESTAMP RETURNING id`).get(n(product_id),String(title),String(recipe_type),n(yield_qty)||1,String(instructions));audit(req.user.id,'UPSERT','RECIPE',info.id,{title});res.status(201).json(recipe(info.id))});
 app.post('/api/recipes/:id/items',minRole(55),(req,res)=>{const {ingredient_product_id,qty,unit='UNIT',waste_percent=0,notes=''}=req.body||{};if(!ingredient_product_id||n(qty)<=0)return res.status(400).json({error:'INVALID_INGREDIENT'});const info=db.prepare('INSERT INTO recipe_items(recipe_id,ingredient_product_id,qty,unit,waste_percent,notes) VALUES(?,?,?,?,?,?)').run(n(req.params.id),n(ingredient_product_id),n(qty),String(unit),n(waste_percent),String(notes));audit(req.user.id,'ADD_INGREDIENT','RECIPE',req.params.id,{item_id:info.lastInsertRowid});res.status(201).json(recipe(req.params.id))});
 app.delete('/api/recipes/:id/items/:itemId',minRole(55),(req,res)=>{db.prepare('DELETE FROM recipe_items WHERE id=? AND recipe_id=?').run(n(req.params.itemId),n(req.params.id));audit(req.user.id,'DELETE_INGREDIENT','RECIPE',req.params.id);res.json(recipe(req.params.id))});
 app.post('/api/stock-counts',minRole(55),(req,res)=>{const {product_id,counted_qty,reason='Conferência física'}=req.body||{},p=db.prepare('SELECT * FROM products WHERE id=?').get(n(product_id));if(!p)return res.status(404).json({error:'PRODUCT_NOT_FOUND'});const variance=n(counted_qty)-n(p.stock);const info=db.prepare('INSERT INTO stock_counts(product_id,expected_qty,counted_qty,variance_qty,reason,user_id) VALUES(?,?,?,?,?,?)').run(p.id,p.stock,n(counted_qty),variance,String(reason),req.user.id);db.prepare('UPDATE products SET stock=? WHERE id=?').run(n(counted_qty),p.id);db.prepare("INSERT INTO stock_movements(product_id,type,qty,reference_type,reference_id,user_id,notes) VALUES(?,'COUNT_VARIANCE',?,'STOCK_COUNT',?,?,?)").run(p.id,variance,String(info.lastInsertRowid),req.user.id,String(reason));audit(req.user.id,'COUNT','STOCK',p.id,{variance});res.status(201).json({id:info.lastInsertRowid,expected:p.stock,counted:n(counted_qty),variance})});
 app.get('/api/smart-closing',minRole(50),(_req,res)=>{const cs=db.prepare("SELECT * FROM cash_sessions WHERE status='OPEN' ORDER BY id DESC LIMIT 1").get();const sales=cs?db.prepare("SELECT COALESCE(SUM(total),0) revenue FROM sales WHERE cash_session_id=? AND status='PAID'").get(cs.id):{revenue:0};const cogs=cs?db.prepare(`SELECT COALESCE(SUM(si.qty*si.unit_cost),0) v FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE s.cash_session_id=? AND s.status='PAID'`).get(cs.id).v:0;const exp=db.prepare("SELECT COALESCE(SUM(amount),0) v FROM expenses WHERE date(created_at)=date('now')").get().v;const revenue=n(sales.revenue),gross=Math.max(0,revenue-n(cogs)-n(exp));const reserve=gross*.20,reinvest=gross*.15,buffer=Math.max(revenue*.10,100);const safe=Math.max(0,gross-reserve-reinvest-buffer);const risk=safe<=0?'HIGH':safe<revenue*.1?'MEDIUM':'LOW';res.json({cash_session_id:cs?.id||null,revenue,cogs:n(cogs),expenses:n(exp),gross_after_costs:gross,safety_reserve:reserve,reinvestment:reinvest,operating_buffer:buffer,safe_owner_withdrawal:safe,risk_level:risk,rationale:risk==='HIGH'?'Não retirar: custos e reserva operacional consomem o caixa disponível.':'Retirada limitada após custos, reserva de segurança, reinvestimento e capital operacional.'})});
}
