const API=(import.meta.env.VITE_API_URL||'/api').replace(/\/+$/,'');
let token=localStorage.getItem('nexus_hospitality_token')||'';
export function setAuthToken(v){token=v||'';if(token)localStorage.setItem('nexus_hospitality_token',token);else localStorage.removeItem('nexus_hospitality_token')}
async function request(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;let res;try{res=await fetch(`${API}${path}`,{...options,headers})}catch(cause){const e=new Error('API do NEXUS Hospitality indisponível. Confirme que o servidor está ativo na porta 8989.');e.code='API_UNREACHABLE';e.cause=cause;throw e}const data=await res.json().catch(()=>({}));if(!res.ok){const e=new Error(data.message||data.error||`Erro HTTP ${res.status}`);e.code=data.error;e.status=res.status;throw e}return data}
export const api={

  smartInventory:()=>request('/inventory/smart'),createSmartProduct:body=>request('/inventory/smart-product',{method:'POST',body:JSON.stringify(body)}),updateInventoryProfile:(id,body)=>request(`/inventory/${id}/profile`,{method:'PATCH',body:JSON.stringify(body)}),cashMovement:body=>request('/cash-movements',{method:'POST',body:JSON.stringify(body)}),cashMovements:()=>request('/cash-movements/current'),
  customers:()=>request('/customers'),createCustomer:body=>request('/customers',{method:'POST',body:JSON.stringify(body)}),reservations:()=>request('/reservations'),createReservation:body=>request('/reservations',{method:'POST',body:JSON.stringify(body)}),reservationStatus:(id,status)=>request(`/reservations/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}),
  delivery:()=>request('/delivery'),createDelivery:body=>request('/delivery',{method:'POST',body:JSON.stringify(body)}),deliveryStatus:(id,status)=>request(`/delivery/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}),eventsV06:()=>request('/events-v06'),createEventV06:body=>request('/events-v06',{method:'POST',body:JSON.stringify(body)}),addEventCost:(id,body)=>request(`/events-v06/${id}/costs`,{method:'POST',body:JSON.stringify(body)}),
  fiscalCaptures:()=>request('/fiscal-captures'),createFiscalCapture:body=>request('/fiscal-captures',{method:'POST',body:JSON.stringify(body)}),executiveReport:()=>request('/reports/executive'),
  login:body=>request('/auth/login',{method:'POST',body:JSON.stringify(body)}),logout:()=>request('/auth/logout',{method:'POST'}),me:()=>request('/auth/me'),changePassword:body=>request('/auth/change-password',{method:'POST',body:JSON.stringify(body)}),capabilities:()=>request('/auth/capabilities'),
  dashboard:()=>request('/dashboard'),products:()=>request('/products'),createProduct:body=>request('/products',{method:'POST',body:JSON.stringify(body)}),updateProduct:(id,body)=>request(`/products/${id}`,{method:'PATCH',body:JSON.stringify(body)}),aiBrief:()=>request('/ai/operations-brief'),createSale:body=>request('/sales-v1',{method:'POST',body:JSON.stringify(body)}),
  currentCash:()=>request('/cash-sessions/current'),openCash:body=>request('/cash-sessions/open',{method:'POST',body:JSON.stringify(body)}),closeCash:(id,body)=>request(`/cash-sessions/${id}/close-v1`,{method:'POST',body:JSON.stringify(body)}),
  employees:()=>request('/employees'),createEmployee:body=>request('/employees',{method:'POST',body:JSON.stringify(body)}),users:()=>request('/users'),createUser:body=>request('/users',{method:'POST',body:JSON.stringify(body)}),audit:()=>request('/audit'),
  performance:()=>request('/performance'),createIncentive:body=>request('/incentive-rules',{method:'POST',body:JSON.stringify(body)}),createTip:body=>request('/tips',{method:'POST',body:JSON.stringify(body)}),

  opsSummary:()=>request('/operations/summary'),tables:()=>request('/tables'),createTable:body=>request('/tables',{method:'POST',body:JSON.stringify(body)}),openTable:(id,body)=>request(`/tables/${id}/open`,{method:'POST',body:JSON.stringify(body)}),
  ordersV03:()=>request('/orders-v03'),orderV03:id=>request(`/orders-v03/${id}`),addOrderItem:(id,body)=>request(`/orders-v03/${id}/items`,{method:'POST',body:JSON.stringify(body)}),setOrderItemStatus:(id,status)=>request(`/order-items/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}),deleteOrderItem:id=>request(`/order-items/${id}`,{method:'DELETE'}),transferOrder:(id,table_id)=>request(`/orders-v03/${id}/transfer`,{method:'POST',body:JSON.stringify({table_id})}),splitOrder:(id,body)=>request(`/orders-v03/${id}/split`,{method:'POST',body:JSON.stringify(body)}),closeOrder:(id,body)=>request(`/orders-v1/${id}/close`,{method:'POST',body:JSON.stringify(body)}),kitchen:()=>request('/kitchen'),
  beverageControl:()=>request('/beverage-control'),updateBeverage:(id,body)=>request(`/products/${id}/beverage`,{method:'PATCH',body:JSON.stringify(body)}),adjustStock:(id,body)=>request(`/products/${id}/stock-adjust`,{method:'POST',body:JSON.stringify(body)}),
  suppliersV03:()=>request('/suppliers-v03'),createSupplierV03:body=>request('/suppliers-v03',{method:'POST',body:JSON.stringify(body)}),quotesV03:()=>request('/quotes-v03'),createQuoteV03:body=>request('/quotes-v03',{method:'POST',body:JSON.stringify(body)}),quoteV03:id=>request(`/quotes-v03/${id}`),addQuoteItemV03:(id,body)=>request(`/quotes-v03/${id}/items`,{method:'POST',body:JSON.stringify(body)}),bestQuoteV03:id=>request(`/quotes-v03/${id}/best`),
  recipes:()=>request('/recipes'),recipe:id=>request(`/recipes/${id}`),saveRecipe:body=>request('/recipes',{method:'POST',body:JSON.stringify(body)}),addRecipeItem:(id,body)=>request(`/recipes/${id}/items`,{method:'POST',body:JSON.stringify(body)}),deleteRecipeItem:(id,itemId)=>request(`/recipes/${id}/items/${itemId}`,{method:'DELETE'}),stockCount:body=>request('/stock-counts',{method:'POST',body:JSON.stringify(body)}),smartClosing:()=>request('/smart-closing'),
  orders:()=>request('/orders'),createOrder:body=>request('/orders',{method:'POST',body:JSON.stringify(body)}),expenses:()=>request('/expenses'),createExpense:body=>request('/expenses',{method:'POST',body:JSON.stringify(body)}),goals:()=>request('/goals'),createGoal:body=>request('/goals',{method:'POST',body:JSON.stringify(body)}),closingPlan:revenue=>request(`/closing-plan?revenue=${encodeURIComponent(revenue)}`),settings:()=>request('/settings'),updateSettings:body=>request('/settings',{method:'PUT',body:JSON.stringify(body)})
};
