import React,{useMemo,useState}from'react';
import{api}from'./api.js';
import{brl,numberBR,parseBR}from'./format.js';

const payMethods=[['PIX','PIX'],['DINHEIRO','Dinheiro'],['DEBITO','Débito'],['CREDITO','Crédito'],['MISTO','Misto'],['FIADO','Fiado / Conta']];

export default function SmartPOSV07({products=[],employees=[],cash,onDone}){
 const[cart,setCart]=useState([]),[search,setSearch]=useState(''),[category,setCategory]=useState('TODOS'),[payment,setPayment]=useState('PIX'),[employee,setEmployee]=useState(''),[tip,setTip]=useState(''),[received,setReceived]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[move,setMove]=useState(null),[moveAmount,setMoveAmount]=useState(''),[moveText,setMoveText]=useState('');
 const categories=useMemo(()=>['TODOS',...Array.from(new Set(products.map(p=>String(p.category||'Outros').trim()||'Outros'))).sort()], [products]);
 const filtered=useMemo(()=>products.filter(p=>{const okCat=category==='TODOS'||String(p.category||'Outros')===category;const q=`${p.name} ${p.category||''} ${p.barcode||''}`.toLowerCase();return okCat&&q.includes(search.toLowerCase())}),[products,category,search]);
 const subtotal=cart.reduce((s,x)=>s+x.salePrice*x.qty,0),tipValue=parseBR(tip),total=subtotal+tipValue,receivedValue=parseBR(received),change=payment==='DINHEIRO'?Math.max(0,receivedValue-total):0;
 function price(p,mode){if(mode==='DOSE')return Number(p.smart_dose_price||p.price||0);if(mode==='BOTTLE')return Number(p.smart_package_price||p.price||0);return Number(p.price||0)}
 function add(p,mode='UNIT'){const key=`${p.id}-${mode}`;setCart(c=>{const found=c.find(x=>x.key===key);return found?c.map(x=>x.key===key?{...x,qty:x.qty+1}:x):[...c,{...p,key,mode,qty:1,salePrice:price(p,mode)}]})}
 function qty(key,d){setCart(c=>c.map(x=>x.key===key?{...x,qty:Math.max(0,x.qty+d)}:x).filter(x=>x.qty>0))}
 async function finish(){if(!cash)return setMsg('Abra o caixa antes de vender.');if(!cart.length)return setMsg('Adicione pelo menos um produto.');if(payment==='DINHEIRO'&&receivedValue>0&&receivedValue<total)return setMsg('Valor recebido menor que o total.');setBusy(true);try{await api.createSale({payment_method:payment,employee_id:employee||null,tip_amount:tipValue,items:cart.map(x=>({product_id:x.id,qty:x.qty,mode:x.mode}))});setCart([]);setTip('');setReceived('');setMsg(`Venda concluída • ${brl(total)}${payment==='DINHEIRO'&&change>0?` • Troco ${brl(change)}`:''}`);await onDone?.()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function movement(){setBusy(true);try{await api.cashMovement({type:move,amount:parseBR(moveAmount),description:moveText});setMsg(`${move==='SANGRIA'?'Sangria':'Suprimento'} registrado: ${brl(parseBR(moveAmount))}`);setMove(null);setMoveAmount('');setMoveText('');await onDone?.()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <section className="pos07-shell">
  <header className="pos07-header"><div><span>SMART POS • V0.7</span><h2>Caixa Operacional</h2><p>Venda rápida, baixa automática e operação de balcão em tela grande.</p></div><div className="pos07-cash-status"><i className={cash?'on':''}/><div><small>CAIXA</small><strong>{cash?'ABERTO':'FECHADO'}</strong></div></div></header>
  {msg&&<div className="pos07-message">✦ {msg}</div>}
  <div className="pos07-toolbar"><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar produto, categoria ou código..."/><button onClick={()=>setMove('SUPRIMENTO')}>＋ SUPRIMENTO</button><button onClick={()=>setMove('SANGRIA')}>− SANGRIA</button><button className="danger" onClick={()=>setCart([])}>LIMPAR VENDA</button></div>
  <div className="pos07-categories">{categories.map(c=><button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
  <div className="pos07-layout"><div className="pos07-catalog"><div className="pos07-grid">{filtered.map(p=><article className="pos07-product" key={p.id}><div className="pos07-img">{p.image_url?<img src={p.image_url} alt=""/>:<b>{String(p.name||'N')[0]}</b>}</div><small>{p.category||'Produto'}</small><h3>{p.name}</h3>{p.smart_sell_dose?<div className="pos07-modes"><button onClick={()=>add(p,'DOSE')}><span>DOSE {p.smart_dose_size?`${numberBR(p.smart_dose_size,0)} ml`:''}</span><b>{brl(p.smart_dose_price)}</b></button><button onClick={()=>add(p,'BOTTLE')}><span>GARRAFA</span><b>{brl(p.smart_package_price)}</b></button></div>:<button className="pos07-add" onClick={()=>add(p,'UNIT')}>ADICIONAR <b>{brl(p.price)}</b></button>}</article>)}</div>{!filtered.length&&<div className="pos07-empty">Nenhum produto encontrado.</div>}</div>
   <aside className="pos07-cart"><div className="pos07-cart-head"><div><span>VENDA ATUAL</span><small>{cart.reduce((s,x)=>s+x.qty,0)} item(ns)</small></div><strong>{brl(total)}</strong></div><div className="pos07-items">{cart.map(x=><div className="pos07-item" key={x.key}><div className="pos07-item-main"><b>{x.name}</b><small>{x.mode==='DOSE'?'Dose':x.mode==='BOTTLE'?'Garrafa':'Unidade'} • {brl(x.salePrice)}</small></div><div className="pos07-stepper"><button onClick={()=>qty(x.key,-1)}>−</button><strong>{x.qty}</strong><button onClick={()=>qty(x.key,1)}>＋</button></div><b className="pos07-line-total">{brl(x.salePrice*x.qty)}</b></div>)}{!cart.length&&<div className="pos07-empty">Toque em um produto para iniciar a venda.</div>}</div>
    <div className="pos07-checkout"><div className="pos07-fields"><label>Atendente<select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">Usuário atual</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Gorjeta<div className="pos07-money"><span>R$</span><input inputMode="decimal" value={tip} onChange={e=>setTip(e.target.value)}/></div></label></div><div className="pos07-payments">{payMethods.map(([v,l])=><button key={v} className={payment===v?'active':''} onClick={()=>setPayment(v)}>{l}</button>)}</div>{payment==='DINHEIRO'&&<div className="pos07-cash-received"><label>Valor recebido<div className="pos07-money big"><span>R$</span><input inputMode="decimal" value={received} onChange={e=>setReceived(e.target.value)} placeholder="0,00"/></div></label><div><small>TROCO</small><strong>{brl(change)}</strong></div></div>}<div className="pos07-totals"><div><span>Subtotal</span><b>{brl(subtotal)}</b></div><div><span>Gorjeta</span><b>{brl(tipValue)}</b></div><div className="grand"><span>TOTAL</span><strong>{brl(total)}</strong></div></div><button className="pos07-finish" disabled={busy||!cart.length} onClick={finish}>{busy?'PROCESSANDO...':'RECEBER / FINALIZAR VENDA'}</button><small className="pos07-auto">Estoque • Caixa • Financeiro • Metas • IA atualizados automaticamente</small></div>
   </aside></div>
  {move&&<div className="pos07-modal-backdrop" onClick={()=>setMove(null)}><div className="pos07-modal" onClick={e=>e.stopPropagation()}><span>CAIXA</span><h3>{move==='SANGRIA'?'Registrar sangria':'Registrar suprimento'}</h3><label>Valor<div className="pos07-money big"><span>R$</span><input autoFocus value={moveAmount} onChange={e=>setMoveAmount(e.target.value)}/></div></label><label>Motivo<input value={moveText} onChange={e=>setMoveText(e.target.value)} placeholder="Ex.: pagamento fornecedor / reforço de troco"/></label><div><button onClick={()=>setMove(null)}>CANCELAR</button><button className="primary" disabled={busy} onClick={movement}>CONFIRMAR</button></div></div></div>}
 </section>
}
